# Core Data Structures in Pandas
Pandas is built on two main data structures:

**Series** → One-dimensional (like a single column in Excel)

**DataFrame** → Two-dimensional (like a full spreadsheet or SQL table)

### Series — 1D Labeled Array
A Series is like a list with labels (index).

import pandas as pd
s = pd.Series([10,20,30,40,50])
print(s)

Notice the automatic index: 0, 1, 2, 3

You can also define custom index:

In [12]:
custom_index = pd.Series([10,20,30,40,50],index = ["A","B","c","D","E"])
print(custom_index)

A    10
B    20
c    30
D    40
E    50
dtype: int64

### DataFrame — 2D Labeled Table
A DataFrame is like a dictionary of Series — multiple columns with labels.

In [19]:
data = {
    "name" : ["Alice","Bob","John"],
    "age"  : [25,28,30],
    "city" : ["Delhi","Mumbai","Bangalore"]
}

df = pd.DataFrame(data)
df

    name  age       city
0  Alice   25      Delhi
1    Bob   28     Mumbai
2   John   30  Bangalore

Each column in a DataFrame is a Series.

### Index and Labels
Every Series and DataFrame has an Index — it helps with:

Fast lookups

Aligning data

Merging & joining

Time series operations

In [15]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [16]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [23]:
df.index = ["a","b","c"]
df.columns = ["NAME","AGE","CITY"]
df

    NAME  AGE       CITY
a  Alice   25      Delhi
b    Bob   28     Mumbai
c   John   30  Bangalore

### Why Learn These Well?
Most Pandas operations are built on these foundations:

Selection

Filtering

Merging

Aggregation

Understanding Series & DataFrames will make everything else easier.

### Summary
**Series** = 1D array with labels 

**DataFrame** = 2D table with rows + columns

Both come with index and are the heart of Pandas

## Practice Questions

### Q1 Create Series

Create a series:

[5,10,15,20]

Index:

["a","b","c","d"]

In [30]:
s = pd.Series([5,10,15,20],index = ["a","b","c","d"])
s

a     5
b    10
c    15
d    20
dtype: int64

### Q2 Create DataFrame

Create DataFrame:

Name    Marks    City

Ali      85      Surat

Sara     90      Ahmedabad

Zain     88      Baroda

In [26]:
Data = {
    "Name" : ["Ali","Sara","Zain"],
    "Marks" : [85,90,88],
    "City"  : ["Surat","Ahmedabad","Baroda"]
}
Data_Frame = pd.DataFrame(Data)
Data_Frame

   Name  Marks       City
0   Ali     85      Surat
1  Sara     90  Ahmedabad
2  Zain     88     Baroda

### Q3 Print
df.index

df.columns

In [28]:
print(Data_Frame.index)

RangeIndex(start=0, stop=3, step=1)

In [29]:
print(Data_Frame.columns)

Index(['Name', 'Marks', 'City'], dtype='object')

### Q4 Change Labels

Change:

columns → Name Marks City

index → s1 s2 s3

In [33]:
Data_Frame.index = ["s1","s2","s3"]
Data_Frame.columns = ["name","marks","city"]
Data_Frame

    name  marks       city
s1   Ali     85      Surat
s2  Sara     90  Ahmedabad
s3  Zain     88     Baroda