# Creating DataFrames
Let’s look at different ways to create a Pandas DataFrame — the core data structure you’ll be using 90% of the time in data science.

### From Python Lists

In [1]:
import pandas as pd

data = [
    ["Alice", 25],
    ["Bob", 30],
    ["Charlie", 35]
]

df = pd.DataFrame(data, columns=["Name", "Age"])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

### From Dictionary of Lists
Most common and readable format:

In [3]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35]
}

df = pd.DataFrame(data)
df

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

Each key becomes a column, and each list is the column data.

### From NumPy Arrays

In [5]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
df = pd.DataFrame(arr, columns=["A", "B"])
df

   A  B
0  1  2
1  3  4

Make sure to provide column names!

### From CSV Files

In [21]:
df = pd.read_csv("data.csv")
df

   Name  Age       City
0   Ali   22      Surat
1  Sara   24  Ahmedabad
2  Zain   23     Baroda

Use options like:

sep, header, names, index_col, usecols, nrows, etc.

### Example:

In [22]:
pd.read_csv("data.csv", usecols=["Name"])

   Name
0   Ali
1  Sara
2  Zain

### From Excel Files

In [17]:
df = pd.read_excel("data.xlsx.xlsx")
df

   Name  Age       City
0   Ali   22      Surat
1  Sara   24  Ahmedabad
2  Zain   23     Baroda

In [15]:
import os
os.getcwd()

'C:\\python-Data-Science\\02_Pandas\\anaconda_projects\\db'

In [16]:
os.listdir()

['.ipynb_checkpoints',
 'Core Data Structures in Pandas.ipynb',
 'Creating DataFrames.ipynb',
 'data.xlsx.xlsx',
 'mydb.sqlite',
 'project_filebrowser.db']

You may need to install openpyxl or xlrd:

In [23]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.1.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

### From JSON

In [27]:
df = pd.read_json("data.json.txt")
df

      Name  Age       City
0    Alice   25  Ahmedabad
1      Bob   30      Surat
2  Charlie   35   Vadodara

Can also read from a URL or string.

### From SQL Databases

import sqlite3
 
conn = sqlite3.connect("mydb.sqlite")

df = pd.read_sql("SELECT * FROM users", conn)

### From the Web (Example: CSV from URL)

In [29]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

### EDA (Exploratory Data Analysis)
Exploratory Data Analysis (EDA) is an essential first step in any data science project.

It involves taking a deep look at the dataset to understand its structure, spot patterns, identify anomalies, and uncover relationships between variables. This process includes generating summary statistics, checking for missing or duplicate data, and creating visualizations like histograms, box plots, and scatter plots. The goal of EDA is to get a clear picture of what the data is telling you before applying any analysis or machine learning models.

By exploring the data thoroughly, you can make better decisions about how to clean, transform, and model it effectively.

Once your DataFrame is ready, run these to understand your data:

In [30]:
df.head()         # First 5 rows
df.tail()         # Last 5 rows
df.info()         # Column info: types, non-nulls
df.describe()     # Stats for numeric columns
df.columns        # List of column names
df.shape          # (rows, columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

(244, 7)

### Summary

You can create DataFrames from lists, dicts, arrays, files, web, and SQL

Use .head(), .info(), .describe() to quickly explore any dataset