# Data Transformation
Once your data is clean, the next step is to reshape, reformat, and reorder it as needed for analysis. 

Pandas gives you plenty of flexible tools to do this.

In [1]:
import pandas as pd 
df = pd.read_csv("data.json.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

## Sorting & Ranking
### Sort by Values

In [2]:
df.sort_values("Year") # Ascending sort

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [3]:
df.sort_values("Year", ascending = False) # Descending sort

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [4]:
df2 = df.sort_values(["Year","IMDb"]).copy()
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

df.sort_values(["Age", "Salary"]) sorts the DataFrame first by the "Age" column, and if there are ties (i.e., two or more rows with the same "Age"), it will sort by the "Salary" column.

### Reset Index
If you want the index to start from 0 and be sequential, you can reset it using reset_index()

In [5]:
df2.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
3,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
4,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,7,Hrithik Roshan,War,2019,Action,475,6.5
7,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
9,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
10,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
11,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [6]:
 #df2.reset_index(drop = True, inplace = True) # Reset the index and drop the old index

In [7]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

### Sort by Index

In [8]:
df2.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

The df.sort_index() function is used to sort the DataFrame based on its index values. If the index is not in a sequential order (e.g., you have dropped rows or performed other operations that change the index), you can use sort_index() to restore it to a sorted order.

### Ranking
The .rank() function in pandas is used to assign ranks to numeric values in a column, like scores or points. By default, it gives the average rank to tied values, which can result in decimal numbers. For example, if two people share the top score, they both get a rank of 1.5. You can customize the ranking behavior using the method parameter. One useful option is method='dense', which assigns the same rank to ties but doesn’t leave gaps in the ranking sequence. This is helpful when you want a clean, consecutive ranking system without skips.

In [9]:
df2["Rank"] = df2["IMDb"].rank(ascending = False)  # Default: average method
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,10.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,9.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,8.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,12.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,11.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [10]:
df2["Rank"] = df2["IMDb"].rank(ascending = False, method = "dense")
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

### Renaming Columns & Index

In [11]:
df2.rename(columns = {"IMDb" : "imdb"} , inplace = True)
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),imdb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [12]:
df2.rename(index = {0:"row0",1:"row1"})

,Actor,Film,Year,Genre,BoxOffice(INR Crore),imdb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
row1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
row0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [13]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),imdb,Rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

To rename all columns:

In [16]:
df2.columns = ["actor","film","year","genre","box office","imdb","rank"].copy()
df2

,actor,film,year,genre,box office,imdb,rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

In [18]:
df2

,actor,film,year,genre,box office,imdb,rank
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0

### Changing Column Order
Just pass a new list of column names:

In [20]:
df2 = df2[["actor","genre","box office","film","year","imdb","rank"]]   # Reorder as desired
df2

,actor,genre,box office,film,year,imdb,rank
2,Aamir Khan,Biography,2024,Dangal,2016,8.4,1.0
1,Salman Khan,Action,565,Tiger Zinda Hai,2017,6.0,9.0
10,Varun Dhawan,Romantic Comedy,201,Badrinath Ki Dulhania,2017,6.1,8.0
4,Ranveer Singh,Historical,585,Padmaavat,2018,7.0,6.0
6,Rajkummar Rao,Horror Comedy,180,Stree,2018,7.5,4.0
5,Ayushmann Khurrana,Thriller,111,Andhadhun,2018,8.3,2.0
7,Hrithik Roshan,Action,475,War,2019,6.5,7.0
8,Akshay Kumar,Comedy,318,Good Newwz,2019,7.0,6.0
11,Vicky Kaushal,Action,342,Uri: The Surgical Strike,2019,8.2,3.0
3,Ranbir Kapoor,Fantasy,431,Brahmastra,2022,5.6,11.0
9,Kartik Aaryan,Horror Comedy,266,Bhool Bhulaiyaa 2,2022,5.9,10.0
0,Shah Rukh Khan,Action,1050,Pathaan,2023,7.2,5.0

In [21]:
df2

,actor,genre,box office,film,year,imdb,rank
2,Aamir Khan,Biography,2024,Dangal,2016,8.4,1.0
1,Salman Khan,Action,565,Tiger Zinda Hai,2017,6.0,9.0
10,Varun Dhawan,Romantic Comedy,201,Badrinath Ki Dulhania,2017,6.1,8.0
4,Ranveer Singh,Historical,585,Padmaavat,2018,7.0,6.0
6,Rajkummar Rao,Horror Comedy,180,Stree,2018,7.5,4.0
5,Ayushmann Khurrana,Thriller,111,Andhadhun,2018,8.3,2.0
7,Hrithik Roshan,Action,475,War,2019,6.5,7.0
8,Akshay Kumar,Comedy,318,Good Newwz,2019,7.0,6.0
11,Vicky Kaushal,Action,342,Uri: The Surgical Strike,2019,8.2,3.0
3,Ranbir Kapoor,Fantasy,431,Brahmastra,2022,5.6,11.0
9,Kartik Aaryan,Horror Comedy,266,Bhool Bhulaiyaa 2,2022,5.9,10.0
0,Shah Rukh Khan,Action,1050,Pathaan,2023,7.2,5.0

You can also move one column to the front:

In [24]:
cols = ["genre"] + [col for col in df2.columns if col != "genre"]
df2 = df2[cols]
df2

,genre,actor,box office,film,year,imdb,rank
2,Biography,Aamir Khan,2024,Dangal,2016,8.4,1.0
1,Action,Salman Khan,565,Tiger Zinda Hai,2017,6.0,9.0
10,Romantic Comedy,Varun Dhawan,201,Badrinath Ki Dulhania,2017,6.1,8.0
4,Historical,Ranveer Singh,585,Padmaavat,2018,7.0,6.0
6,Horror Comedy,Rajkummar Rao,180,Stree,2018,7.5,4.0
5,Thriller,Ayushmann Khurrana,111,Andhadhun,2018,8.3,2.0
7,Action,Hrithik Roshan,475,War,2019,6.5,7.0
8,Comedy,Akshay Kumar,318,Good Newwz,2019,7.0,6.0
11,Action,Vicky Kaushal,342,Uri: The Surgical Strike,2019,8.2,3.0
3,Fantasy,Ranbir Kapoor,431,Brahmastra,2022,5.6,11.0
9,Horror Comedy,Kartik Aaryan,266,Bhool Bhulaiyaa 2,2022,5.9,10.0
0,Action,Shah Rukh Khan,1050,Pathaan,2023,7.2,5.0

# Summary
Sort, rank, and rename to prepare your data

Reordering and reshaping are key for EDA and visualization