In [2]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Math": [85, 78, 92],
    "Science": [90, 82, 89],
    "English": [88, 85, 94]
}

df = pd.DataFrame(data)
df

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

# Section 1 — Melt (Wide → Long)
## Question 1

### Convert the DataFrame from wide format to long format using melt().

### Keep Name as the identifier column.

In [8]:
df_long = df.melt(
    id_vars = "Name",
    value_vars = ["Math","Science","English"],
    var_name = "Subject",
    value_name = "Score"
)

df_long

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

# Section 2 — Pivot (Long → Wide)
## Question 2

### Using the melted DataFrame, convert the data back to wide format using pivot().

In [12]:
df_wide = df_long.pivot(
    index="Name",
    columns="Subject",
    values="Score"
)

df_wide

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

# Section 3 — Pivot Table (Handling duplicates)

In [13]:
data2 = {
    "Name": ["Alice", "Alice", "Bob", "Bob"],
    "Subject": ["Math", "Math", "Science", "Science"],
    "Score": [85, 80, 82, 88]
}

df2 = pd.DataFrame(data2)
df2

    Name  Subject  Score
0  Alice     Math     85
1  Alice     Math     80
2    Bob  Science     82
3    Bob  Science     88

## Question 3

### Use pivot_table() to create a table where:

In [20]:
df_pivot_table = df2.pivot_table(
    index = "Name",
    columns = "Subject",
    values = "Score",
    aggfunc = "mean"
)

df_pivot_table

Subject  Math  Science
Name
Alice    82.5      NaN
Bob       NaN     85.0