In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali","Sara","Zain","Aisha","Omar","Sara"],
    "Age": [22,24,np.nan,26,30,24],
    "City": ["Surat","Ahmedabad","Baroda","Surat","Delhi","Ahmedabad"],
    "Score": [85,90,88,92,80,90],
    "Salary": [30000,40000,35000,45000,50000,40000]
}

df = pd.DataFrame(data)
df

    Name   Age       City  Score  Salary
0    Ali  22.0      Surat     85   30000
1   Sara  24.0  Ahmedabad     90   40000
2   Zain   NaN     Baroda     88   35000
3  Aisha  26.0      Surat     92   45000
4   Omar  30.0      Delhi     80   50000
5   Sara  24.0  Ahmedabad     90   40000

# Section 1 — Basic EDA
## Q1

## Show first 5 rows

In [2]:
df.head()

    Name   Age       City  Score  Salary
0    Ali  22.0      Surat     85   30000
1   Sara  24.0  Ahmedabad     90   40000
2   Zain   NaN     Baroda     88   35000
3  Aisha  26.0      Surat     92   45000
4   Omar  30.0      Delhi     80   50000

## Q2

## Show last 3 rows

In [3]:
df.tail()

    Name   Age       City  Score  Salary
1   Sara  24.0  Ahmedabad     90   40000
2   Zain   NaN     Baroda     88   35000
3  Aisha  26.0      Surat     92   45000
4   Omar  30.0      Delhi     80   50000
5   Sara  24.0  Ahmedabad     90   40000

In [4]:
df.loc[3:5]

    Name   Age       City  Score  Salary
3  Aisha  26.0      Surat     92   45000
4   Omar  30.0      Delhi     80   50000
5   Sara  24.0  Ahmedabad     90   40000

## Q3

## Display:

### df.info()

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     5 non-null      float64
 2   City    6 non-null      object
 3   Score   6 non-null      int64
 4   Salary  6 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

## Q4

### Show statistical summary of dataset

In [6]:
df.describe()

            Age      Score        Salary
count   5.00000   6.000000      6.000000
mean   25.20000  87.500000  40000.000000
std     3.03315   4.370355   7071.067812
min    22.00000  80.000000  30000.000000
25%    24.00000  85.750000  36250.000000
50%    24.00000  89.000000  40000.000000
75%    26.00000  90.000000  43750.000000
max    30.00000  92.000000  50000.000000

describe() automatically calculate karta hai:

Statistic	:    Meaning

count	  :      total values

mean	   :     average

std	     :       standard deviation

min	     :       smallest value

max	      :      largest value

25%, 50%, 75%	: quartiles

## Q5

## Print:

### df.columns
### df.shape

In [7]:
df.columns

Index(['Name', 'Age', 'City', 'Score', 'Salary'], dtype='object')

In [8]:
df.shape

(6, 5)

# Section 2 — Selection
## Q6

## Select Name column

In [9]:
df["Name"]

0      Ali
1     Sara
2     Zain
3    Aisha
4     Omar
5     Sara
Name: Name, dtype: object

## Q7

## Select Name and Salary columns

In [10]:
df[["Name","Salary"]]

    Name  Salary
0    Ali   30000
1   Sara   40000
2   Zain   35000
3  Aisha   45000
4   Omar   50000
5   Sara   40000

## Q8

## Select first row using loc

In [11]:
df.loc[0]

Name        Ali
Age        22.0
City      Surat
Score        85
Salary    30000
Name: 0, dtype: object

## Q9

## Select second row using iloc

In [12]:
df.iloc[1]

Name           Sara
Age            24.0
City      Ahmedabad
Score            90
Salary        40000
Name: 1, dtype: object

## Q10

## Select value of Name at row 0

In [13]:
df.loc[0,"Name"]

'Ali'

# Section 3 — Filtering
## Q11

## Show rows where:

### Age > 24

In [14]:
df[df["Age"] > 24]

    Name   Age   City  Score  Salary
3  Aisha  26.0  Surat     92   45000
4   Omar  30.0  Delhi     80   50000

## Q12

## Students from Surat

In [15]:
df[df["City"] == "Surat" ]

    Name   Age   City  Score  Salary
0    Ali  22.0  Surat     85   30000
3  Aisha  26.0  Surat     92   45000

## Q13

## Students where:

### Score > 85 AND City == Surat

In [16]:
df[(df["Score"] > 85) & (df["City"] == "Surat")]

    Name   Age   City  Score  Salary
3  Aisha  26.0  Surat     92   45000

## Q14

## Use query() to filter:

### Age > 23

In [17]:
df.query("Age > 23")

    Name   Age       City  Score  Salary
1   Sara  24.0  Ahmedabad     90   40000
3  Aisha  26.0      Surat     92   45000
4   Omar  30.0      Delhi     80   50000
5   Sara  24.0  Ahmedabad     90   40000

# Section 4 — Data Cleaning
## Q15

## Check missing values per column

In [18]:
df.isnull().sum()

Name      0
Age       1
City      0
Score     0
Salary    0
dtype: int64

## Q16

## Fill missing Age with mean

In [19]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

    Name   Age       City  Score  Salary
0    Ali  22.0      Surat     85   30000
1   Sara  24.0  Ahmedabad     90   40000
2   Zain  25.2     Baroda     88   35000
3  Aisha  26.0      Surat     92   45000
4   Omar  30.0      Delhi     80   50000
5   Sara  24.0  Ahmedabad     90   40000

## Q17

## Check duplicate rows

In [20]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

## Q18

## Remove duplicate rows

In [21]:
df.drop_duplicates(inplace=True)
df

    Name   Age       City  Score  Salary
0    Ali  22.0      Surat     85   30000
1   Sara  24.0  Ahmedabad     90   40000
2   Zain  25.2     Baroda     88   35000
3  Aisha  26.0      Surat     92   45000
4   Omar  30.0      Delhi     80   50000

# Section 5 — String Operations
## Q19

## Convert Name column to lowercase

In [22]:
df["Name"] = df["Name"].str.lower()
df

    Name   Age       City  Score  Salary
0    ali  22.0      Surat     85   30000
1   sara  24.0  Ahmedabad     90   40000
2   zain  25.2     Baroda     88   35000
3  aisha  26.0      Surat     92   45000
4   omar  30.0      Delhi     80   50000

## Q20

## Check rows where city contains "surat"

In [23]:
df["City"].str.contains("Surat")

0     True
1    False
2    False
3     True
4    False
Name: City, dtype: bool

In [24]:
df[df["City"].str.contains("surat", case = False)]

    Name   Age   City  Score  Salary
0    ali  22.0  Surat     85   30000
3  aisha  26.0  Surat     92   45000

# Section 6 — Data Transformation
## Q21

## Sort dataframe by Age

In [25]:
df.sort_values("Age")

    Name   Age       City  Score  Salary
0    ali  22.0      Surat     85   30000
1   sara  24.0  Ahmedabad     90   40000
2   zain  25.2     Baroda     88   35000
3  aisha  26.0      Surat     92   45000
4   omar  30.0      Delhi     80   50000

## Q22

## Sort dataframe by Salary descending

In [26]:
df.sort_values("Salary",ascending=False)

    Name   Age       City  Score  Salary
4   omar  30.0      Delhi     80   50000
3  aisha  26.0      Surat     92   45000
1   sara  24.0  Ahmedabad     90   40000
2   zain  25.2     Baroda     88   35000
0    ali  22.0      Surat     85   30000

## Q23

## Create new column:

#### Age_Group

#### Rule:

##### Age >= 25 → Adult
##### Age < 25 → Young

In [27]:
def isyoung(x):
    return "Adult" if x>= 25 else "Young"

df["Age Group"] =  df["Age"].apply(isyoung)
df

    Name   Age       City  Score  Salary Age Group
0    ali  22.0      Surat     85   30000     Young
1   sara  24.0  Ahmedabad     90   40000     Young
2   zain  25.2     Baroda     88   35000     Adult
3  aisha  26.0      Surat     92   45000     Adult
4   omar  30.0      Delhi     80   50000     Adult

## Q24

## Create ranking based on Score

In [28]:
df["Rank"] = df["Marks"].rank(method = "dense",ascending = False)
df

KeyError: 'Marks'

## Q25

## Rename column:

## Score → Marks

In [ ]:
df = df.rename(columns = {"Score":"Marks"})
df

## Q26

## Change column order to:

## Name City Age Salary Score

In [ ]:
df = df[["Name","City","Age","Salary","Marks"]]
df

## Final Question (Real Data Task)
## Q27

### Show students who:

### Age > 23
### AND
### Score > 85

### Sorted by Score descending

In [29]:
df.query("Age > 23 and Marks > 85").sort_values("Marks",ascending = False)

UndefinedVariableError: name 'Marks' is not defined