# Sales Data Analysis using Pandas and NumPy

## Objective
The objective of this project is to analyze retail sales data using Pandas and NumPy.
This project includes data inspection, cleaning, transformation, and analysis.

## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Create dataset

In [2]:
data = {
    "Order_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Order_Date": ["2024-01-05", "2024-01-07", "2024-02-10", "2024-02-15", "2024-03-01",
                   "2024-03-05", "2024-03-20", "2024-04-01", "2024-04-07", "2024-04-15"],
    "Customer_Name": ["Ali", "Sara", "John", "Aisha", "Omar", "Zoya", "Ahmed", "Fatima", "Ali", "Sara"],
    "City": ["Ahmedabad", "Surat", "Ahmedabad", "Mumbai", "Surat", "Delhi", "Mumbai", "Ahmedabad", "Surat", np.nan],
    "Category": ["Electronics", "Clothing", "Electronics", "Grocery", "Clothing",
                 "Electronics", "Grocery", "Clothing", "Electronics", "Grocery"],
    "Product": ["Laptop", "T-Shirt", "Mouse", "Rice", "Jeans", "Keyboard", "Oil", "Kurti", "Monitor", "Sugar"],
    "Quantity": [1, 2, 3, 5, 2, 1, 4, 2, 1, 3],
    "Price": [55000, 800, 500, 60, 1200, 1500, 140, 900, 12000, 45],
    "Payment_Mode": ["UPI", "Cash", "Card", "UPI", "Cash", "Card", "UPI", "Cash", "Card", "UPI"]
}

df = pd.DataFrame(data)
df

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Price,Payment_Mode
0,101,2024-01-05,Ali,Ahmedabad,Electronics,Laptop,1,55000,UPI
1,102,2024-01-07,Sara,Surat,Clothing,T-Shirt,2,800,Cash
2,103,2024-02-10,John,Ahmedabad,Electronics,Mouse,3,500,Card
3,104,2024-02-15,Aisha,Mumbai,Grocery,Rice,5,60,UPI
4,105,2024-03-01,Omar,Surat,Clothing,Jeans,2,1200,Cash
5,106,2024-03-05,Zoya,Delhi,Electronics,Keyboard,1,1500,Card
6,107,2024-03-20,Ahmed,Mumbai,Grocery,Oil,4,140,UPI
7,108,2024-04-01,Fatima,Ahmedabad,Clothing,Kurti,2,900,Cash
8,109,2024-04-07,Ali,Surat,Electronics,Monitor,1,12000,Card
9,110,2024-04-15,Sara,NaN,Grocery,Sugar,3,45,UPI

## Create Total Sales Column

In [3]:
df["Total_Sales"] = df["Quantity"] * df["Price"]
df

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Price,Payment_Mode,Total_Sales
0,101,2024-01-05,Ali,Ahmedabad,Electronics,Laptop,1,55000,UPI,55000
1,102,2024-01-07,Sara,Surat,Clothing,T-Shirt,2,800,Cash,1600
2,103,2024-02-10,John,Ahmedabad,Electronics,Mouse,3,500,Card,1500
3,104,2024-02-15,Aisha,Mumbai,Grocery,Rice,5,60,UPI,300
4,105,2024-03-01,Omar,Surat,Clothing,Jeans,2,1200,Cash,2400
5,106,2024-03-05,Zoya,Delhi,Electronics,Keyboard,1,1500,Card,1500
6,107,2024-03-20,Ahmed,Mumbai,Grocery,Oil,4,140,UPI,560
7,108,2024-04-01,Fatima,Ahmedabad,Clothing,Kurti,2,900,Cash,1800
8,109,2024-04-07,Ali,Surat,Electronics,Monitor,1,12000,Card,12000
9,110,2024-04-15,Sara,NaN,Grocery,Sugar,3,45,UPI,135

## Basic Data Inspection

In [4]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Price,Payment_Mode,Total_Sales
0,101,2024-01-05,Ali,Ahmedabad,Electronics,Laptop,1,55000,UPI,55000
1,102,2024-01-07,Sara,Surat,Clothing,T-Shirt,2,800,Cash,1600
2,103,2024-02-10,John,Ahmedabad,Electronics,Mouse,3,500,Card,1500
3,104,2024-02-15,Aisha,Mumbai,Grocery,Rice,5,60,UPI,300
4,105,2024-03-01,Omar,Surat,Clothing,Jeans,2,1200,Cash,2400

In [5]:
df.tail()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Price,Payment_Mode,Total_Sales
5,106,2024-03-05,Zoya,Delhi,Electronics,Keyboard,1,1500,Card,1500
6,107,2024-03-20,Ahmed,Mumbai,Grocery,Oil,4,140,UPI,560
7,108,2024-04-01,Fatima,Ahmedabad,Clothing,Kurti,2,900,Cash,1800
8,109,2024-04-07,Ali,Surat,Electronics,Monitor,1,12000,Card,12000
9,110,2024-04-15,Sara,NaN,Grocery,Sugar,3,45,UPI,135

In [6]:
df.shape

(10, 10)

In [7]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'City', 'Category',
       'Product', 'Quantity', 'Price', 'Payment_Mode', 'Total_Sales'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       10 non-null     int64
 1   Order_Date     10 non-null     object
 2   Customer_Name  10 non-null     object
 3   City           9 non-null      object
 4   Category       10 non-null     object
 5   Product        10 non-null     object
 6   Quantity       10 non-null     int64
 7   Price          10 non-null     int64
 8   Payment_Mode   10 non-null     object
 9   Total_Sales    10 non-null     int64
dtypes: int64(4), object(6)
memory usage: 932.0+ bytes

In [9]:
df.describe()

        Order_ID   Quantity         Price   Total_Sales
count   10.00000  10.000000     10.000000     10.000000
mean   105.50000   2.400000   7214.500000   7679.500000
std      3.02765   1.349897  17172.086919  16982.784167
min    101.00000   1.000000     45.000000    135.000000
25%    103.25000   1.250000    230.000000    795.000000
50%    105.50000   2.000000    850.000000   1550.000000
75%    107.75000   3.000000   1425.000000   2250.000000
max    110.00000   5.000000  55000.000000  55000.000000

## Checking Missing Values

In [10]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
City             1
Category         0
Product          0
Quantity         0
Price            0
Payment_Mode     0
Total_Sales      0
dtype: int64

## Handling Missing Values

In [11]:
df["City"] = df["City"].fillna(df["City"].mode()[0])
df

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Price,Payment_Mode,Total_Sales
0,101,2024-01-05,Ali,Ahmedabad,Electronics,Laptop,1,55000,UPI,55000
1,102,2024-01-07,Sara,Surat,Clothing,T-Shirt,2,800,Cash,1600
2,103,2024-02-10,John,Ahmedabad,Electronics,Mouse,3,500,Card,1500
3,104,2024-02-15,Aisha,Mumbai,Grocery,Rice,5,60,UPI,300
4,105,2024-03-01,Omar,Surat,Clothing,Jeans,2,1200,Cash,2400
5,106,2024-03-05,Zoya,Delhi,Electronics,Keyboard,1,1500,Card,1500
6,107,2024-03-20,Ahmed,Mumbai,Grocery,Oil,4,140,UPI,560
7,108,2024-04-01,Fatima,Ahmedabad,Clothing,Kurti,2,900,Cash,1800
8,109,2024-04-07,Ali,Surat,Electronics,Monitor,1,12000,Card,12000
9,110,2024-04-15,Sara,Ahmedabad,Grocery,Sugar,3,45,UPI,135

In [12]:
df.isnull().sum()

Order_ID         0
Order_Date       0
Customer_Name    0
City             0
Category         0
Product          0
Quantity         0
Price            0
Payment_Mode     0
Total_Sales      0
dtype: int64

## Converting Order_Date to Datetime

In [13]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       10 non-null     int64
 1   Order_Date     10 non-null     datetime64[ns]
 2   Customer_Name  10 non-null     object
 3   City           10 non-null     object
 4   Category       10 non-null     object
 5   Product        10 non-null     object
 6   Quantity       10 non-null     int64
 7   Price          10 non-null     int64
 8   Payment_Mode   10 non-null     object
 9   Total_Sales    10 non-null     int64
dtypes: datetime64[ns](1), int64(4), object(5)
memory usage: 932.0+ bytes

## Feature Engineering

In [14]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Day"] = df["Order_Date"].dt.day
df["Day_Name"] = df["Order_Date"].dt.day_name()

df

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Price,Payment_Mode,Total_Sales,Year,Month,Day,Day_Name
0,101,2024-01-05,Ali,Ahmedabad,Electronics,Laptop,1,55000,UPI,55000,2024,1,5,Friday
1,102,2024-01-07,Sara,Surat,Clothing,T-Shirt,2,800,Cash,1600,2024,1,7,Sunday
2,103,2024-02-10,John,Ahmedabad,Electronics,Mouse,3,500,Card,1500,2024,2,10,Saturday
3,104,2024-02-15,Aisha,Mumbai,Grocery,Rice,5,60,UPI,300,2024,2,15,Thursday
4,105,2024-03-01,Omar,Surat,Clothing,Jeans,2,1200,Cash,2400,2024,3,1,Friday
5,106,2024-03-05,Zoya,Delhi,Electronics,Keyboard,1,1500,Card,1500,2024,3,5,Tuesday
6,107,2024-03-20,Ahmed,Mumbai,Grocery,Oil,4,140,UPI,560,2024,3,20,Wednesday
7,108,2024-04-01,Fatima,Ahmedabad,Clothing,Kurti,2,900,Cash,1800,2024,4,1,Monday
8,109,2024-04-07,Ali,Surat,Electronics,Monitor,1,12000,Card,12000,2024,4,7,Sunday
9,110,2024-04-15,Sara,Ahmedabad,Grocery,Sugar,3,45,UPI,135,2024,4,15,Monday

## Overall Sales Analysis

In [15]:
df["Total_Sales"].sum()

np.int64(76795)

In [16]:
df["Total_Sales"].mean()

np.float64(7679.5)

In [17]:
df["Total_Sales"].max()

55000

In [18]:
df["Total_Sales"].min()

135

## Category-wise Sales Analysis

In [19]:
df.groupby("Category")["Total_Sales"].sum()

Category
Clothing        5800
Electronics    70000
Grocery          995
Name: Total_Sales, dtype: int64

In [20]:
df.groupby("Category")["Total_Sales"].mean()

Category
Clothing        1933.333333
Electronics    17500.000000
Grocery          331.666667
Name: Total_Sales, dtype: float64

## City-wise Sales Analysis

In [21]:
df.groupby("City")["Total_Sales"].sum()

City
Ahmedabad    58435
Delhi         1500
Mumbai         860
Surat        16000
Name: Total_Sales, dtype: int64

In [22]:
df.groupby("City")["Total_Sales"].mean()

City
Ahmedabad    14608.750000
Delhi         1500.000000
Mumbai         430.000000
Surat         5333.333333
Name: Total_Sales, dtype: float64

## Monthly Sales Analysis

In [23]:
df.groupby("Month")["Total_Sales"].sum()

Month
1    56600
2     1800
3     4460
4    13935
Name: Total_Sales, dtype: int64

## Product-wise Sales Analysis

In [24]:
df.groupby("Product")["Total_Sales"].sum().sort_values(ascending=False)

Product
Laptop      55000
Monitor     12000
Jeans        2400
Kurti        1800
T-Shirt      1600
Keyboard     1500
Mouse        1500
Oil           560
Rice          300
Sugar         135
Name: Total_Sales, dtype: int64

## Payment Mode Analysis

In [25]:
df["Payment_Mode"].value_counts()

Payment_Mode
UPI     4
Cash    3
Card    3
Name: count, dtype: int64

## Quantity Sold by Category

In [26]:
df.groupby("Category")["Quantity"].sum()

Category
Clothing        6
Electronics     6
Grocery        12
Name: Quantity, dtype: int64

## Top 5 Highest Sales Records

In [27]:
df.sort_values(by="Total_Sales", ascending=False).head()

,Order_ID,Order_Date,Customer_Name,City,Category,Product,Quantity,Price,Payment_Mode,Total_Sales,Year,Month,Day,Day_Name
0,101,2024-01-05,Ali,Ahmedabad,Electronics,Laptop,1,55000,UPI,55000,2024,1,5,Friday
8,109,2024-04-07,Ali,Surat,Electronics,Monitor,1,12000,Card,12000,2024,4,7,Sunday
4,105,2024-03-01,Omar,Surat,Clothing,Jeans,2,1200,Cash,2400,2024,3,1,Friday
7,108,2024-04-01,Fatima,Ahmedabad,Clothing,Kurti,2,900,Cash,1800,2024,4,1,Monday
1,102,2024-01-07,Sara,Surat,Clothing,T-Shirt,2,800,Cash,1600,2024,1,7,Sunday

## Duplicate Check

In [28]:
df.duplicated().sum()

np.int64(0)

## Final Insights

- Electronics category generated the highest revenue among all categories.
- Ahmedabad, Surat, and Mumbai contributed significantly to total sales.
- UPI and Cash were commonly used payment modes in the dataset.
- Some products such as Laptop and Monitor contributed much more revenue than low-price grocery products.
- Monthly sales analysis helps identify which months performed better.

## Conclusion

This project helped in understanding how to work with a sales dataset using Pandas and NumPy.
It included data creation, inspection, missing value handling, datetime conversion, feature engineering, and grouped analysis.